version: '3'

# docker-compose -f docker-compose.yml build
# docker-compose -f docker-compose.yml up -d
services:
  app:
    build: ./app
    container_name: flask_kai
    command: gunicorn --bind 0.0.0.0:5000 app:app # WSGI server
    environment:
      - DATABASE_URL=postgresql://kai:291297@db:5432/homedb # путь до бд, см. db service
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kai
      - POSTGRES_PASSWORD=291297
      - POSTGRES_DB=homedb
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=kai_by@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=291297 # если сменить здесь, то нужно удалить контентер
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0 # чтобы не было косяков с nginx лушче в одну сеть с app
      - PGADMIN_LISTEN_PORT=5555
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./static:/home/web/default/static
    depends_on:
      - app
      - pgadmin